<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>ShiftClub.Client.Updater</AssemblyName>
    <RootNamespace>ShiftClub.Client.Updater</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\ShiftClub.Shared\ShiftClub.Shared.csproj" />
  </ItemGroup>

</Project>
